version: '3.8'


services:
  db_postgres:
    image: postgres:14-alpine
    ports:
      - 3600:3600
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    restart: always

    
