server:
  port: 8080
  servlet:
    context-path: /todo
spring:
  datasource:
    url: ${PSQL_HOST}
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${PSQL_DDL}
  sql:
    init:
      mode: ${PSQL_MODE}