server:
  port: 8080
  servlet:
    context-path: /todo
spring:
  datasource:
    url: jdbc:postgresql://${PSQL_HOST}:5432/postgres
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger

auth:
  http:
    headerName: ${AUTH_HEADER}
    authToken: ${AUTH_TOKEN}